#!/bin/bash

set -eu

if [[ "${CIRCLE_BRANCH}" != 'master' ]] ; then
  BUILD_ENV=development
  REACT_APP_AUTH_ENABLED=REACT_APP_AUTH_ENABLED_DEV
  REACT_APP_AUTH_ISSUER=REACT_APP_AUTH_ISSUER_DEV
  REACT_APP_AUTH_LOGOUT_URI=REACT_APP_AUTH_LOGOUT_URI_DEV
  REACT_APP_AUTH_REDIRECT_URI=REACT_APP_AUTH_REDIRECT_URI_DEV
  REACT_APP_AUTH_CLIENT_ID=REACT_APP_AUTH_CLIENT_ID_DEV
  REACT_APP_API_BASE_URL=REACT_APP_API_BASE_URL_DEV
  REACT_APP_SKETCH_URL=REACT_APP_SKETCH_URL_DEV
else
  echo "Supply production environment"
  exit 1
fi

cat > .env << EOF

REACT_APP_AUTH_ENABLED=${!REACT_APP_AUTH_ENABLED}
REACT_APP_AUTH_ISSUER=${!REACT_APP_AUTH_ISSUER}
REACT_APP_AUTH_LOGOUT_URI=${!REACT_APP_AUTH_LOGOUT_URI}
REACT_APP_AUTH_REDIRECT_URI=${!REACT_APP_AUTH_REDIRECT_URI}
REACT_APP_AUTH_CLIENT_ID=${!REACT_APP_AUTH_CLIENT_ID}
REACT_APP_API_BASE_URL=${!REACT_APP_API_BASE_URL}
REACT_APP_SKETCH_URL=${!REACT_APP_SKETCH_URL}

EOF
